import type { ScanResult } from '../types';

export const DEMO_DATA: Record<string, ScanResult> = {
  restaurant: {
    url: 'https://mariostrattoria.example.com',
    timestamp: Date.now(),
    title: "Mario's Trattoria — Authentic Italian Cuisine",
    lines: [
      {
        id: 'restaurant-identity',
        name: 'Restaurant Identity',
        colorDark: '#FF6B6B',
        colorLight: '#E74C3C',
        visible: true,
        focused: false,
        stations: [
          { id: 'rest-id-1', lineId: 'restaurant-identity', label: 'Business Name', value: "Mario's Trattoria", confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: 'name', raw: '{"@type":"Restaurant","name":"Mario\'s Trattoria"}' }] },
          { id: 'rest-id-2', lineId: 'restaurant-identity', label: 'Business Type', value: 'Italian Restaurant', confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: '@type', raw: 'Restaurant' }] },
          { id: 'rest-id-3', lineId: 'restaurant-identity', label: 'Description', value: 'Family-owned Italian restaurant serving authentic Neapolitan cuisine since 1987', confidence: 0.9, evidence: [{ source: 'Meta', selector: 'description', raw: 'Family-owned Italian restaurant serving authentic Neapolitan cuisine since 1987' }] },
          { id: 'rest-id-4', lineId: 'restaurant-identity', label: 'Location', value: 'Brooklyn, NY', confidence: 0.85, evidence: [{ source: 'JSON-LD', selector: 'address.addressLocality', raw: '{"addressLocality":"Brooklyn","addressRegion":"NY"}' }] },
        ],
      },
      {
        id: 'restaurant-contacts',
        name: 'Restaurant Contacts',
        colorDark: '#4ECDC4',
        colorLight: '#2980B9',
        visible: true,
        focused: false,
        stations: [
          { id: 'rest-ct-1', lineId: 'restaurant-contacts', label: 'Phone', value: '(718) 555-0142', confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: 'telephone', raw: '+17185550142' }] },
          { id: 'rest-ct-2', lineId: 'restaurant-contacts', label: 'Email', value: 'info@mariostrattoria.com', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'a[href^="mailto:"]', raw: '<a href="mailto:info@mariostrattoria.com">' }] },
          { id: 'rest-ct-3', lineId: 'restaurant-contacts', label: 'Address', value: '247 Court St, Brooklyn, NY 11201', confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: 'address', raw: '{"streetAddress":"247 Court St","addressLocality":"Brooklyn"}' }] },
          { id: 'rest-ct-4', lineId: 'restaurant-contacts', label: 'Hours', value: 'Mon-Thu: 11am-10pm; Fri-Sat: 11am-11pm; Sun: 12pm-9pm', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: 'openingHoursSpecification', raw: '[{"dayOfWeek":"Monday","opens":"11:00","closes":"22:00"}]' }] },
          { id: 'rest-ct-5', lineId: 'restaurant-contacts', label: 'Phone', value: '(718) 555-0199', confidence: 0.7, evidence: [{ source: 'Regex', selector: 'body text', raw: 'Catering: (718) 555-0199' }] },
        ],
      },
      {
        id: 'restaurant-services',
        name: 'Restaurant Services',
        colorDark: '#45B7D1',
        colorLight: '#27AE60',
        visible: true,
        focused: false,
        stations: [
          { id: 'rest-sv-1', lineId: 'restaurant-services', label: 'Service', value: 'Dine-In', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'h3 > list > li', raw: 'Dine-In' }] },
          { id: 'rest-sv-2', lineId: 'restaurant-services', label: 'Service', value: 'Takeout & Delivery', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'h3 > list > li', raw: 'Takeout & Delivery' }] },
          { id: 'rest-sv-3', lineId: 'restaurant-services', label: 'Service', value: 'Private Event Catering', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'h3 > list > li', raw: 'Private Event Catering' }] },
          { id: 'rest-sv-4', lineId: 'restaurant-services', label: 'Service', value: 'Wine Bar', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'h3 > list > li', raw: 'Wine Bar' }] },
          { id: 'rest-sv-5', lineId: 'restaurant-services', label: 'Cuisine', value: 'Italian, Pizza, Pasta, Brooklyn', confidence: 0.7, evidence: [{ source: 'Meta', selector: 'keywords', raw: 'Italian, Pizza, Pasta, Brooklyn, Restaurant' }] },
          // Add intersection station that will be detected by the smart system
          { id: 'rest-sv-intersection', lineId: 'restaurant-services', label: 'Intersection', value: 'Mario\'s Catering Service', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'div.catering-info', raw: 'Mario\'s Catering Service - Brooklyn, NY' }] },
        ],
      },
      {
        id: 'restaurant-pages',
        name: 'Restaurant Pages',
        colorDark: '#F7DC6F',
        colorLight: '#F39C12',
        visible: true,
        focused: false,
        stations: [
          { id: 'rest-pg-1', lineId: 'restaurant-pages', label: 'Page', value: 'Menu', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/menu"]', raw: '/menu' }] },
          { id: 'rest-pg-2', lineId: 'restaurant-pages', label: 'Page', value: 'Our Story', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/about"]', raw: '/about' }] },
          { id: 'rest-pg-3', lineId: 'restaurant-pages', label: 'Page', value: 'Gallery', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/gallery"]', raw: '/gallery' }] },
          { id: 'rest-pg-4', lineId: 'restaurant-pages', label: 'Page', value: 'Contact Us', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/contact"]', raw: '/contact' }] },
          { id: 'rest-pg-5', lineId: 'restaurant-pages', label: 'Page', value: 'Reservations', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/reservations"]', raw: '/reservations' }] },
          { id: 'rest-pg-6', lineId: 'restaurant-pages', label: 'Page', value: 'Catering', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/catering"]', raw: '/catering' }] },
          // Add intersection station that will be detected by the smart system
          { id: 'rest-pg-intersection', lineId: 'restaurant-pages', label: 'Page', value: 'Catering Information', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'section.catering-details', raw: 'Mario\'s Catering Information - Brooklyn, NY' }] },
        ],
      },
      {
        id: 'restaurant-entities',
        name: 'Restaurant Entities',
        colorDark: '#BB8FCE',
        colorLight: '#8E44AD',
        visible: true,
        focused: false,
        stations: [
          { id: 'rest-en-1', lineId: 'restaurant-entities', label: 'Person', value: 'Mario Rossi', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: 'founder.name', raw: 'Mario Rossi' }] },
          { id: 'rest-en-2', lineId: 'restaurant-entities', label: 'Person', value: 'Chef Giuseppe Rossi', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'img[alt="Chef Giuseppe"]', raw: 'Chef Giuseppe Rossi' }] },
          { id: 'rest-en-3', lineId: 'restaurant-entities', label: 'Partner', value: 'Brooklyn Wine Co.', confidence: 0.7, evidence: [{ source: 'HTML', selector: 'img[alt="Brooklyn Wine Co."]', raw: 'Brooklyn Wine Co.' }] },
        ],
      },
      {
        id: 'restaurant-tech',
        name: 'Restaurant Tech',
        colorDark: '#82E0AA',
        colorLight: '#16A085',
        visible: true,
        focused: false,
        stations: [
          { id: 'rest-tc-1', lineId: 'restaurant-tech', label: 'CMS', value: 'WordPress', confidence: 0.95, evidence: [{ source: 'Script analysis', selector: 'signature: wp-content', raw: 'wp-content' }] },
          { id: 'rest-tc-2', lineId: 'restaurant-tech', label: 'Analytics', value: 'Google Analytics', confidence: 0.9, evidence: [{ source: 'Script analysis', selector: 'signature: google-analytics.com', raw: 'google-analytics.com/analytics.js' }] },
          { id: 'rest-tc-3', lineId: 'restaurant-tech', label: 'Framework', value: 'jQuery', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: jquery.min.js', raw: 'jquery.min.js' }] },
          { id: 'rest-tc-4', lineId: 'restaurant-tech', label: 'Design', value: 'Responsive Design', confidence: 0.8, evidence: [{ source: 'Meta', selector: 'meta[name="viewport"]', raw: 'width=device-width, initial-scale=1' }] },
        ],
      },
    ],
    transfers: [
      { id: 'rest-tr-1', stationIds: ['rest-id-4', 'rest-ct-3'], lineIds: ['restaurant-identity', 'restaurant-contacts'], reason: '"Brooklyn, NY" found in address' },
      { id: 'rest-tr-2', stationIds: ['rest-sv-intersection', 'rest-pg-intersection'], lineIds: ['restaurant-services', 'restaurant-pages'], reason: 'Business connection: Catering services and information' },
      { id: 'rest-tr-3', stationIds: ['rest-id-1', 'rest-en-1'], lineIds: ['restaurant-identity', 'restaurant-entities'], reason: 'Similar values: Mario' },
      { id: 'rest-tr-4', stationIds: ['rest-sv-intersection', 'rest-ct-1'], lineIds: ['restaurant-services', 'restaurant-contacts'], reason: 'Contact connection: Catering phone service' },
    ],
  },

  tech: {
    url: 'https://novatech.example.com',
    timestamp: Date.now(),
    title: 'NovaTech Solutions — Enterprise Cloud Infrastructure',
    lines: [
      {
        id: 'tech-identity',
        name: 'Tech Identity',
        colorDark: '#FF6B6B',
        colorLight: '#E74C3C',
        visible: true,
        focused: false,
        stations: [
          { id: 'tech-id-1', lineId: 'tech-identity', label: 'Company Name', value: 'NovaTech Solutions', confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: 'name', raw: '{"@type":"Organization","name":"NovaTech Solutions"}' }] },
          { id: 'tech-id-2', lineId: 'tech-identity', label: 'Business Type', value: 'Technology Company', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: '@type', raw: 'Organization' }] },
          { id: 'tech-id-3', lineId: 'tech-identity', label: 'Description', value: 'Enterprise cloud infrastructure and DevOps solutions for modern businesses', confidence: 0.9, evidence: [{ source: 'Meta', selector: 'og:description', raw: 'Enterprise cloud infrastructure and DevOps solutions' }] },
          { id: 'tech-id-4', lineId: 'tech-identity', label: 'Location', value: 'San Francisco, CA', confidence: 0.85, evidence: [{ source: 'JSON-LD', selector: 'address', raw: '{"addressLocality":"San Francisco","addressRegion":"CA"}' }] },
          { id: 'tech-id-5', lineId: 'tech-identity', label: 'Category', value: 'Cloud, DevOps, SaaS', confidence: 0.7, evidence: [{ source: 'Meta', selector: 'keywords', raw: 'Cloud, DevOps, SaaS, Infrastructure' }] },
        ],
      },
      {
        id: 'tech-contacts',
        name: 'Tech Contacts',
        colorDark: '#4ECDC4',
        colorLight: '#2980B9',
        visible: true,
        focused: false,
        stations: [
          { id: 'tech-ct-1', lineId: 'tech-contacts', label: 'Email', value: 'hello@novatech.io', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'a[href^="mailto:"]', raw: '<a href="mailto:hello@novatech.io">' }] },
          { id: 'tech-ct-2', lineId: 'tech-contacts', label: 'Phone', value: '(415) 555-0234', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'a[href^="tel:"]', raw: '<a href="tel:+14155550234">' }] },
          { id: 'tech-ct-3', lineId: 'tech-contacts', label: 'Address', value: '100 Market St, Suite 400, San Francisco, CA 94105', confidence: 0.8, evidence: [{ source: 'JSON-LD', selector: 'address', raw: '{"streetAddress":"100 Market St"}' }] },
        ],
      },
      {
        id: 'tech-services',
        name: 'Tech Services',
        colorDark: '#45B7D1',
        colorLight: '#27AE60',
        visible: true,
        focused: false,
        stations: [
          { id: 'tech-sv-1', lineId: 'tech-services', label: 'Service', value: 'Cloud Migration', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: 'Cloud Migration' }] },
          { id: 'tech-sv-2', lineId: 'tech-services', label: 'Service', value: 'Kubernetes Management', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: 'Kubernetes Management' }] },
          { id: 'tech-sv-3', lineId: 'tech-services', label: 'Service', value: 'CI/CD Pipeline Setup', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: 'CI/CD Pipeline Setup' }] },
          { id: 'tech-sv-4', lineId: 'tech-services', label: 'Service', value: 'Infrastructure Monitoring', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: 'Infrastructure Monitoring' }] },
          { id: 'tech-sv-5', lineId: 'tech-services', label: 'Service', value: 'Security Auditing', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: 'Security Auditing' }] },
          { id: 'tech-sv-6', lineId: 'tech-services', label: 'Service', value: '24/7 Managed Support', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: '24/7 Managed Support' }] },
          // Add intersection station that will be detected by the smart system
          { id: 'tech-sv-intersection', lineId: 'tech-services', label: 'Service', value: 'NovaTech Cloud Solutions', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'div.cloud-info', raw: 'NovaTech Cloud Solutions - San Francisco, CA' }] },
        ],
      },
      {
        id: 'tech-pages',
        name: 'Tech Pages',
        colorDark: '#F7DC6F',
        colorLight: '#F39C12',
        visible: true,
        focused: false,
        stations: [
          { id: 'tech-pg-1', lineId: 'tech-pages', label: 'Services', value: 'Solutions', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/solutions"]', raw: '/solutions' }] },
          { id: 'tech-pg-2', lineId: 'tech-pages', label: 'Pricing', value: 'Pricing Plans', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/pricing"]', raw: '/pricing' }] },
          { id: 'tech-pg-3', lineId: 'tech-pages', label: 'Blog', value: 'Engineering Blog', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/blog"]', raw: '/blog' }] },
          { id: 'tech-pg-4', lineId: 'tech-pages', label: 'About', value: 'About Us', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/about"]', raw: '/about' }] },
          { id: 'tech-pg-5', lineId: 'tech-pages', label: 'Careers', value: 'Join Our Team', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/careers"]', raw: '/careers' }] },
          { id: 'tech-pg-6', lineId: 'tech-pages', label: 'Contact', value: 'Contact Sales', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/contact"]', raw: '/contact' }] },
          { id: 'tech-pg-7', lineId: 'tech-pages', label: 'Page', value: 'Case Studies', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/case-studies"]', raw: '/case-studies' }] },
          // Add intersection station that will be detected by the smart system
          { id: 'tech-pg-intersection', lineId: 'tech-pages', label: 'Page', value: 'Cloud Solutions Information', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'section.solutions-details', raw: 'NovaTech Cloud Solutions Information - San Francisco, CA' }] },
        ],
      },
      {
        id: 'tech-entities',
        name: 'Tech Entities',
        colorDark: '#BB8FCE',
        colorLight: '#8E44AD',
        visible: true,
        focused: false,
        stations: [
          { id: 'tech-en-1', lineId: 'tech-entities', label: 'Person', value: 'Sarah Chen, CEO', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: 'founder.name', raw: 'Sarah Chen' }] },
          { id: 'tech-en-2', lineId: 'tech-entities', label: 'Partner', value: 'AWS', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="AWS Partner"]', raw: 'AWS' }] },
          { id: 'tech-en-3', lineId: 'tech-entities', label: 'Partner', value: 'Google Cloud', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="Google Cloud"]', raw: 'Google Cloud' }] },
          { id: 'tech-en-4', lineId: 'tech-entities', label: 'Partner', value: 'Microsoft Azure', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="Azure"]', raw: 'Microsoft Azure' }] },
        ],
      },
      {
        id: 'tech-platforms',
        name: 'Tech Platforms',
        colorDark: '#82E0AA',
        colorLight: '#16A085',
        visible: true,
        focused: false,
        stations: [
          { id: 'tech-pl-1', lineId: 'tech-platforms', label: 'Framework', value: 'Next.js', confidence: 0.95, evidence: [{ source: 'Script analysis', selector: 'signature: __NEXT_DATA__', raw: '__NEXT_DATA__' }] },
          { id: 'tech-pl-2', lineId: 'tech-platforms', label: 'Framework', value: 'React', confidence: 0.95, evidence: [{ source: 'Script analysis', selector: 'signature: react', raw: 'react' }] },
          { id: 'tech-pl-3', lineId: 'tech-platforms', label: 'Framework', value: 'Tailwind CSS', confidence: 0.9, evidence: [{ source: 'Script analysis', selector: 'signature: tailwindcss', raw: 'tailwindcss' }] },
          { id: 'tech-pl-4', lineId: 'tech-platforms', label: 'Analytics', value: 'Google Tag Manager', confidence: 0.9, evidence: [{ source: 'Script analysis', selector: 'signature: googletagmanager.com', raw: 'googletagmanager.com' }] },
          { id: 'tech-pl-5', lineId: 'tech-platforms', label: 'Marketing', value: 'HubSpot', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: hs-scripts.com', raw: 'js.hs-scripts.com' }] },
          { id: 'tech-pl-6', lineId: 'tech-platforms', label: 'CDN', value: 'Cloudflare', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: cf-ray', raw: 'cf-ray' }] },
          { id: 'tech-pl-7', lineId: 'tech-platforms', label: 'Payment', value: 'Stripe', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: js.stripe.com', raw: 'js.stripe.com' }] },
          { id: 'tech-pl-8', lineId: 'tech-platforms', label: 'Design', value: 'Responsive Design', confidence: 0.8, evidence: [{ source: 'Meta', selector: 'meta[name="viewport"]', raw: 'width=device-width, initial-scale=1' }] },
        ],
      },
    ],
    transfers: [
      { id: 'tech-tr-1', stationIds: ['tech-id-4', 'tech-ct-3'], lineIds: ['tech-identity', 'tech-contacts'], reason: '"San Francisco, CA" found in address' },
      { id: 'tech-tr-2', stationIds: ['tech-sv-intersection', 'tech-pg-intersection'], lineIds: ['tech-services', 'tech-pages'], reason: 'Business connection: Cloud solutions and information' },
      { id: 'tech-tr-3', stationIds: ['tech-id-5', 'tech-sv-2'], lineIds: ['tech-identity', 'tech-services'], reason: 'Similar values: Cloud/DevOps' },
      { id: 'tech-tr-4', stationIds: ['tech-sv-intersection', 'tech-ct-2'], lineIds: ['tech-services', 'tech-contacts'], reason: 'Contact connection: Cloud services email' },
    ],
  },

  retail: {
    url: 'https://greenleafboutique.example.com',
    timestamp: Date.now(),
    title: 'Green Leaf Boutique — Sustainable Fashion & Home',
    lines: [
      {
        id: 'retail-identity',
        name: 'Retail Identity',
        colorDark: '#FF6B6B',
        colorLight: '#E74C3C',
        visible: true,
        focused: false,
        stations: [
          { id: 'retail-id-1', lineId: 'retail-identity', label: 'Business Name', value: 'Green Leaf Boutique', confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: 'name', raw: '{"@type":"Store","name":"Green Leaf Boutique"}' }] },
          { id: 'retail-id-2', lineId: 'retail-identity', label: 'Business Type', value: 'Retail Store', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: '@type', raw: 'Store' }] },
          { id: 'retail-id-3', lineId: 'retail-identity', label: 'Description', value: 'Curated sustainable fashion, home goods, and artisan products', confidence: 0.9, evidence: [{ source: 'Meta', selector: 'og:description', raw: 'Curated sustainable fashion, home goods, and artisan products' }] },
          { id: 'retail-id-4', lineId: 'retail-identity', label: 'Location', value: 'Portland, OR', confidence: 0.85, evidence: [{ source: 'JSON-LD', selector: 'address.addressLocality', raw: '{"addressLocality":"Portland","addressRegion":"OR"}' }] },
        ],
      },
      {
        id: 'retail-contacts',
        name: 'Retail Contacts',
        colorDark: '#4ECDC4',
        colorLight: '#2980B9',
        visible: true,
        focused: false,
        stations: [
          { id: 'retail-ct-1', lineId: 'retail-contacts', label: 'Phone', value: '(503) 555-0178', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'a[href^="tel:"]', raw: '<a href="tel:+15035550178">' }] },
          { id: 'retail-ct-2', lineId: 'retail-contacts', label: 'Email', value: 'hello@greenleafboutique.com', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'a[href^="mailto:"]', raw: '<a href="mailto:hello@greenleafboutique.com">' }] },
          { id: 'retail-ct-3', lineId: 'retail-contacts', label: 'Address', value: '1234 Hawthorne Blvd, Portland, OR 97214', confidence: 0.85, evidence: [{ source: 'JSON-LD', selector: 'address', raw: '{"streetAddress":"1234 Hawthorne Blvd","addressLocality":"Portland"}' }] },
          { id: 'retail-ct-4', lineId: 'retail-contacts', label: 'Hours', value: 'Tue-Sat: 10am-6pm; Sun: 11am-5pm; Mon: Closed', confidence: 0.85, evidence: [{ source: 'JSON-LD', selector: 'openingHoursSpecification', raw: '[{"dayOfWeek":"Tuesday","opens":"10:00","closes":"18:00"}]' }] },
        ],
      },
      {
        id: 'retail-products',
        name: 'Retail Products',
        colorDark: '#45B7D1',
        colorLight: '#27AE60',
        visible: true,
        focused: false,
        stations: [
          { id: 'retail-pr-1', lineId: 'retail-products', label: 'Product', value: 'Organic Cotton Tote', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/shop"]', raw: '/shop' }] },
          { id: 'retail-pr-2', lineId: 'retail-products', label: 'Product', value: 'New Arrivals', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/new"]', raw: '/new-arrivals' }] },
          { id: 'retail-pr-3', lineId: 'retail-products', label: 'Product', value: 'Handmade Jewelry', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'img[alt*="Handmade"]', raw: 'Handmade Jewelry' }] },
          { id: 'retail-pr-4', lineId: 'retail-products', label: 'Product', value: 'Sustainable Fashion', confidence: 0.7, evidence: [{ source: 'Meta', selector: 'keywords', raw: 'Sustainable, Eco-friendly, Artisan, Fashion, Home' }] },
        ],
      },
      {
        id: 'retail-pages',
        name: 'Retail Pages',
        colorDark: '#F7DC6F',
        colorLight: '#F39C12',
        visible: true,
        focused: false,
        stations: [
          { id: 'retail-pg-1', lineId: 'retail-pages', label: 'Products', value: 'Shop All', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/shop"]', raw: '/shop' }] },
          { id: 'retail-pg-2', lineId: 'retail-pages', label: 'Products', value: 'New Arrivals', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/new"]', raw: '/new-arrivals' }] },
          { id: 'retail-pg-3', lineId: 'retail-pages', label: 'About', value: 'Our Mission', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/about"]', raw: '/about' }] },
          { id: 'retail-pg-4', lineId: 'retail-pages', label: 'Blog', value: 'Sustainability Journal', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/journal"]', raw: '/journal' }] },
          { id: 'retail-pg-5', lineId: 'retail-pages', label: 'Contact', value: 'Visit Us', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/visit"]', raw: '/visit' }] },
        ],
      },
      {
        id: 'retail-entities',
        name: 'Retail Entities',
        colorDark: '#BB8FCE',
        colorLight: '#8E44AD',
        visible: true,
        focused: false,
        stations: [
          { id: 'retail-en-1', lineId: 'retail-entities', label: 'Person', value: 'Emma Greenfield, Founder', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: 'founder.name', raw: 'Emma Greenfield' }] },
          { id: 'retail-en-2', lineId: 'retail-entities', label: 'Brand', value: 'Patagonia', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="Patagonia"]', raw: 'Patagonia' }] },
          { id: 'retail-en-3', lineId: 'retail-entities', label: 'Brand', value: 'Everlane', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="Everlane"]', raw: 'Everlane' }] },
          { id: 'retail-en-4', lineId: 'retail-entities', label: 'Brand', value: 'Coyuchi', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="Coyuchi"]', raw: 'Coyuchi' }] },
          { id: 'retail-en-5', lineId: 'retail-entities', label: 'Product', value: 'Organic Cotton Tote', confidence: 0.7, evidence: [{ source: 'JSON-LD', selector: 'Product.name', raw: 'Organic Cotton Tote' }] },
          { id: 'retail-en-6', lineId: 'retail-entities', label: 'Product', value: 'Beeswax Candle Set', confidence: 0.7, evidence: [{ source: 'JSON-LD', selector: 'Product.name', raw: 'Beeswax Candle Set' }] },
        ],
      },
      {
        id: 'retail-tech',
        name: 'Retail Tech',
        colorDark: '#82E0AA',
        colorLight: '#16A085',
        visible: true,
        focused: false,
        stations: [
          { id: 'retail-tc-1', lineId: 'retail-tech', label: 'CMS', value: 'Shopify', confidence: 0.95, evidence: [{ source: 'Script analysis', selector: 'signature: cdn.shopify.com', raw: 'cdn.shopify.com' }] },
          { id: 'retail-tc-2', lineId: 'retail-tech', label: 'Analytics', value: 'Google Analytics', confidence: 0.9, evidence: [{ source: 'Script analysis', selector: 'signature: google-analytics.com', raw: 'google-analytics.com/analytics.js' }] },
          { id: 'retail-tc-3', lineId: 'retail-tech', label: 'Marketing', value: 'Mailchimp', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: mailchimp', raw: 'mailchimp' }] },
          { id: 'retail-tc-4', lineId: 'retail-tech', label: 'Analytics', value: 'Facebook Pixel', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: connect.facebook.net', raw: 'connect.facebook.net' }] },
          { id: 'retail-tc-5', lineId: 'retail-tech', label: 'Design', value: 'Responsive Design', confidence: 0.8, evidence: [{ source: 'Meta', selector: 'meta[name="viewport"]', raw: 'width=device-width, initial-scale=1' }] },
        ],
      },
    ],
    transfers: [
      { id: 'retail-tr-1', stationIds: ['retail-id-4', 'retail-ct-3'], lineIds: ['retail-identity', 'retail-contacts'], reason: '"Portland, OR" found in address' },
      { id: 'retail-tr-2', stationIds: ['retail-id-3', 'retail-pr-4'], lineIds: ['retail-identity', 'retail-products'], reason: 'Similar values: Sustainable' },
      { id: 'retail-tr-3', stationIds: ['retail-en-5', 'retail-pg-2'], lineIds: ['retail-entities', 'retail-pages'], reason: 'Similar values: New products' },
      { id: 'retail-tr-4', stationIds: ['retail-en-5', 'retail-pr-6'], lineIds: ['retail-entities', 'retail-products'], reason: 'Similar values: Organic products' },
    ],
  },
};
