import type { ScanResult } from '../types';

export const DEMO_DATA: Record<string, ScanResult> = {
  restaurant: {
    url: 'https://mariostrattoria.example.com',
    timestamp: Date.now(),
    title: "Mario's Trattoria — Authentic Italian Cuisine",
    lines: [
      {
        id: 'identity',
        name: 'Identity',
        colorDark: '#FF6B6B',
        colorLight: '#E74C3C',
        visible: true,
        focused: false,
        stations: [
          { id: 'id-1', lineId: 'identity', label: 'Business Name', value: "Mario's Trattoria", confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: 'name', raw: '{"@type":"Restaurant","name":"Mario\'s Trattoria"}' }] },
          { id: 'id-2', lineId: 'identity', label: 'Business Type', value: 'Italian Restaurant', confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: '@type', raw: 'Restaurant' }] },
          { id: 'id-3', lineId: 'identity', label: 'Description', value: 'Family-owned Italian restaurant serving authentic Neapolitan cuisine since 1987', confidence: 0.9, evidence: [{ source: 'Meta', selector: 'description', raw: 'Family-owned Italian restaurant serving authentic Neapolitan cuisine since 1987' }] },
          { id: 'id-4', lineId: 'identity', label: 'Location', value: 'Brooklyn, NY', confidence: 0.85, evidence: [{ source: 'JSON-LD', selector: 'address.addressLocality', raw: '{"addressLocality":"Brooklyn","addressRegion":"NY"}' }] },
        ],
      },
      {
        id: 'contacts',
        name: 'Contacts',
        colorDark: '#4ECDC4',
        colorLight: '#2980B9',
        visible: true,
        focused: false,
        stations: [
          { id: 'ct-1', lineId: 'contacts', label: 'Phone', value: '(718) 555-0142', confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: 'telephone', raw: '+17185550142' }] },
          { id: 'ct-2', lineId: 'contacts', label: 'Email', value: 'info@mariostrattoria.com', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'a[href^="mailto:"]', raw: '<a href="mailto:info@mariostrattoria.com">' }] },
          { id: 'ct-3', lineId: 'contacts', label: 'Address', value: '247 Court St, Brooklyn, NY 11201', confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: 'address', raw: '{"streetAddress":"247 Court St","addressLocality":"Brooklyn"}' }] },
          { id: 'ct-4', lineId: 'contacts', label: 'Hours', value: 'Mon-Thu: 11am-10pm; Fri-Sat: 11am-11pm; Sun: 12pm-9pm', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: 'openingHoursSpecification', raw: '[{"dayOfWeek":"Monday","opens":"11:00","closes":"22:00"}]' }] },
          { id: 'ct-5', lineId: 'contacts', label: 'Phone', value: '(718) 555-0199', confidence: 0.7, evidence: [{ source: 'Regex', selector: 'body text', raw: 'Catering: (718) 555-0199' }] },
        ],
      },
      {
        id: 'services',
        name: 'Services',
        colorDark: '#45B7D1',
        colorLight: '#27AE60',
        visible: true,
        focused: false,
        stations: [
          { id: 'sv-1', lineId: 'services', label: 'Service', value: 'Dine-In', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'h3 > list > li', raw: 'Dine-In' }] },
          { id: 'sv-2', lineId: 'services', label: 'Service', value: 'Takeout & Delivery', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'h3 > list > li', raw: 'Takeout & Delivery' }] },
          { id: 'sv-3', lineId: 'services', label: 'Service', value: 'Private Event Catering', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'h3 > list > li', raw: 'Private Event Catering' }] },
          { id: 'sv-4', lineId: 'services', label: 'Service', value: 'Wine Bar', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'h3 > list > li', raw: 'Wine Bar' }] },
          { id: 'sv-5', lineId: 'services', label: 'Keyword', value: 'Italian, Pizza, Pasta, Brooklyn', confidence: 0.7, evidence: [{ source: 'Meta', selector: 'keywords', raw: 'Italian, Pizza, Pasta, Brooklyn, Restaurant' }] },
        ],
      },
      {
        id: 'pages',
        name: 'Pages',
        colorDark: '#F7DC6F',
        colorLight: '#F39C12',
        visible: true,
        focused: false,
        stations: [
          { id: 'pg-1', lineId: 'pages', label: 'Page', value: 'Menu', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/menu"]', raw: '/menu' }] },
          { id: 'pg-2', lineId: 'pages', label: 'About', value: 'Our Story', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/about"]', raw: '/about' }] },
          { id: 'pg-3', lineId: 'pages', label: 'Gallery', value: 'Photo Gallery', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/gallery"]', raw: '/gallery' }] },
          { id: 'pg-4', lineId: 'pages', label: 'Contact', value: 'Contact Us', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/contact"]', raw: '/contact' }] },
          { id: 'pg-5', lineId: 'pages', label: 'Page', value: 'Reservations', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/reservations"]', raw: '/reservations' }] },
          { id: 'pg-6', lineId: 'pages', label: 'Page', value: 'Catering', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/catering"]', raw: '/catering' }] },
        ],
      },
      {
        id: 'entities',
        name: 'Entities',
        colorDark: '#BB8FCE',
        colorLight: '#8E44AD',
        visible: true,
        focused: false,
        stations: [
          { id: 'en-1', lineId: 'entities', label: 'Person', value: 'Mario Rossi', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: 'founder.name', raw: 'Mario Rossi' }] },
          { id: 'en-2', lineId: 'entities', label: 'Person', value: 'Chef Giuseppe Rossi', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'img[alt="Chef Giuseppe"]', raw: 'Chef Giuseppe Rossi' }] },
          { id: 'en-3', lineId: 'entities', label: 'Partner', value: 'Brooklyn Wine Co.', confidence: 0.7, evidence: [{ source: 'HTML', selector: 'img[alt="Brooklyn Wine Co."]', raw: 'Brooklyn Wine Co.' }] },
        ],
      },
      {
        id: 'tech',
        name: 'Tech',
        colorDark: '#82E0AA',
        colorLight: '#16A085',
        visible: true,
        focused: false,
        stations: [
          { id: 'tc-1', lineId: 'tech', label: 'CMS', value: 'WordPress', confidence: 0.95, evidence: [{ source: 'Script analysis', selector: 'signature: wp-content', raw: 'wp-content' }] },
          { id: 'tc-2', lineId: 'tech', label: 'Analytics', value: 'Google Analytics', confidence: 0.9, evidence: [{ source: 'Script analysis', selector: 'signature: google-analytics.com', raw: 'google-analytics.com/analytics.js' }] },
          { id: 'tc-3', lineId: 'tech', label: 'Framework', value: 'jQuery', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: jquery.min.js', raw: 'jquery.min.js' }] },
          { id: 'tc-4', lineId: 'tech', label: 'Design', value: 'Responsive Design', confidence: 0.8, evidence: [{ source: 'Meta', selector: 'meta[name="viewport"]', raw: 'width=device-width, initial-scale=1' }] },
        ],
      },
    ],
    transfers: [
      { id: 'tr-1', stationIds: ['id-4', 'ct-3'], lineIds: ['identity', 'contacts'], reason: '"Brooklyn, NY" found in address' },
      { id: 'tr-2', stationIds: ['sv-3', 'pg-6'], lineIds: ['services', 'pages'], reason: 'Similar values: Catering' },
      { id: 'tr-3', stationIds: ['id-1', 'en-1'], lineIds: ['identity', 'entities'], reason: 'Similar values: Mario' },
    ],
  },

  tech: {
    url: 'https://novatech.example.com',
    timestamp: Date.now(),
    title: 'NovaTech Solutions — Enterprise Cloud Infrastructure',
    lines: [
      {
        id: 'identity',
        name: 'Identity',
        colorDark: '#FF6B6B',
        colorLight: '#E74C3C',
        visible: true,
        focused: false,
        stations: [
          { id: 'id-1', lineId: 'identity', label: 'Business Name', value: 'NovaTech Solutions', confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: 'name', raw: '{"@type":"Organization","name":"NovaTech Solutions"}' }] },
          { id: 'id-2', lineId: 'identity', label: 'Business Type', value: 'Technology Company', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: '@type', raw: 'Organization' }] },
          { id: 'id-3', lineId: 'identity', label: 'Description', value: 'Enterprise cloud infrastructure and DevOps solutions for modern businesses', confidence: 0.9, evidence: [{ source: 'Meta', selector: 'og:description', raw: 'Enterprise cloud infrastructure and DevOps solutions' }] },
          { id: 'id-4', lineId: 'identity', label: 'Location', value: 'San Francisco, CA', confidence: 0.85, evidence: [{ source: 'JSON-LD', selector: 'address', raw: '{"addressLocality":"San Francisco","addressRegion":"CA"}' }] },
          { id: 'id-5', lineId: 'identity', label: 'Category', value: 'Cloud, DevOps, SaaS', confidence: 0.7, evidence: [{ source: 'Meta', selector: 'keywords', raw: 'Cloud, DevOps, SaaS, Infrastructure' }] },
        ],
      },
      {
        id: 'contacts',
        name: 'Contacts',
        colorDark: '#4ECDC4',
        colorLight: '#2980B9',
        visible: true,
        focused: false,
        stations: [
          { id: 'ct-1', lineId: 'contacts', label: 'Email', value: 'hello@novatech.io', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'a[href^="mailto:"]', raw: '<a href="mailto:hello@novatech.io">' }] },
          { id: 'ct-2', lineId: 'contacts', label: 'Phone', value: '(415) 555-0234', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'a[href^="tel:"]', raw: '<a href="tel:+14155550234">' }] },
          { id: 'ct-3', lineId: 'contacts', label: 'Address', value: '100 Market St, Suite 400, San Francisco, CA 94105', confidence: 0.8, evidence: [{ source: 'JSON-LD', selector: 'address', raw: '{"streetAddress":"100 Market St"}' }] },
        ],
      },
      {
        id: 'services',
        name: 'Services',
        colorDark: '#45B7D1',
        colorLight: '#27AE60',
        visible: true,
        focused: false,
        stations: [
          { id: 'sv-1', lineId: 'services', label: 'Service', value: 'Cloud Migration', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: 'Cloud Migration' }] },
          { id: 'sv-2', lineId: 'services', label: 'Service', value: 'Kubernetes Management', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: 'Kubernetes Management' }] },
          { id: 'sv-3', lineId: 'services', label: 'Service', value: 'CI/CD Pipeline Setup', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: 'CI/CD Pipeline Setup' }] },
          { id: 'sv-4', lineId: 'services', label: 'Service', value: 'Infrastructure Monitoring', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: 'Infrastructure Monitoring' }] },
          { id: 'sv-5', lineId: 'services', label: 'Service', value: 'Security Auditing', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: 'Security Auditing' }] },
          { id: 'sv-6', lineId: 'services', label: 'Service', value: '24/7 Managed Support', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'H2 > list > li', raw: '24/7 Managed Support' }] },
        ],
      },
      {
        id: 'pages',
        name: 'Pages',
        colorDark: '#F7DC6F',
        colorLight: '#F39C12',
        visible: true,
        focused: false,
        stations: [
          { id: 'pg-1', lineId: 'pages', label: 'Services', value: 'Solutions', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/solutions"]', raw: '/solutions' }] },
          { id: 'pg-2', lineId: 'pages', label: 'Pricing', value: 'Pricing Plans', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/pricing"]', raw: '/pricing' }] },
          { id: 'pg-3', lineId: 'pages', label: 'Blog', value: 'Engineering Blog', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/blog"]', raw: '/blog' }] },
          { id: 'pg-4', lineId: 'pages', label: 'About', value: 'About Us', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/about"]', raw: '/about' }] },
          { id: 'pg-5', lineId: 'pages', label: 'Careers', value: 'Join Our Team', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/careers"]', raw: '/careers' }] },
          { id: 'pg-6', lineId: 'pages', label: 'Contact', value: 'Contact Sales', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/contact"]', raw: '/contact' }] },
          { id: 'pg-7', lineId: 'pages', label: 'Page', value: 'Case Studies', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/case-studies"]', raw: '/case-studies' }] },
        ],
      },
      {
        id: 'entities',
        name: 'Entities',
        colorDark: '#BB8FCE',
        colorLight: '#8E44AD',
        visible: true,
        focused: false,
        stations: [
          { id: 'en-1', lineId: 'entities', label: 'Person', value: 'Sarah Chen, CEO', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: 'founder.name', raw: 'Sarah Chen' }] },
          { id: 'en-2', lineId: 'entities', label: 'Partner', value: 'AWS', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="AWS Partner"]', raw: 'AWS' }] },
          { id: 'en-3', lineId: 'entities', label: 'Partner', value: 'Google Cloud', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="Google Cloud"]', raw: 'Google Cloud' }] },
          { id: 'en-4', lineId: 'entities', label: 'Partner', value: 'Microsoft Azure', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="Azure"]', raw: 'Microsoft Azure' }] },
        ],
      },
      {
        id: 'tech',
        name: 'Tech',
        colorDark: '#82E0AA',
        colorLight: '#16A085',
        visible: true,
        focused: false,
        stations: [
          { id: 'tc-1', lineId: 'tech', label: 'Framework', value: 'Next.js', confidence: 0.95, evidence: [{ source: 'Script analysis', selector: 'signature: __NEXT_DATA__', raw: '__NEXT_DATA__' }] },
          { id: 'tc-2', lineId: 'tech', label: 'Framework', value: 'React', confidence: 0.95, evidence: [{ source: 'Script analysis', selector: 'signature: react', raw: 'react' }] },
          { id: 'tc-3', lineId: 'tech', label: 'Framework', value: 'Tailwind CSS', confidence: 0.9, evidence: [{ source: 'Script analysis', selector: 'signature: tailwindcss', raw: 'tailwindcss' }] },
          { id: 'tc-4', lineId: 'tech', label: 'Analytics', value: 'Google Tag Manager', confidence: 0.9, evidence: [{ source: 'Script analysis', selector: 'signature: googletagmanager.com', raw: 'googletagmanager.com' }] },
          { id: 'tc-5', lineId: 'tech', label: 'Marketing', value: 'HubSpot', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: hs-scripts.com', raw: 'js.hs-scripts.com' }] },
          { id: 'tc-6', lineId: 'tech', label: 'CDN', value: 'Cloudflare', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: cloudflare', raw: 'cf-ray' }] },
          { id: 'tc-7', lineId: 'tech', label: 'Payment', value: 'Stripe', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: js.stripe.com', raw: 'js.stripe.com' }] },
          { id: 'tc-8', lineId: 'tech', label: 'Design', value: 'Responsive Design', confidence: 0.8, evidence: [{ source: 'Meta', selector: 'meta[name="viewport"]', raw: 'width=device-width, initial-scale=1' }] },
        ],
      },
    ],
    transfers: [
      { id: 'tr-1', stationIds: ['id-4', 'ct-3'], lineIds: ['identity', 'contacts'], reason: '"San Francisco, CA" found in address' },
      { id: 'tr-2', stationIds: ['sv-1', 'pg-1'], lineIds: ['services', 'pages'], reason: 'Similar values: Solutions' },
      { id: 'tr-3', stationIds: ['id-5', 'sv-2'], lineIds: ['identity', 'services'], reason: 'Similar values: Cloud/DevOps' },
    ],
  },

  retail: {
    url: 'https://greenleafboutique.example.com',
    timestamp: Date.now(),
    title: 'Green Leaf Boutique — Sustainable Fashion & Home',
    lines: [
      {
        id: 'identity',
        name: 'Identity',
        colorDark: '#FF6B6B',
        colorLight: '#E74C3C',
        visible: true,
        focused: false,
        stations: [
          { id: 'id-1', lineId: 'identity', label: 'Business Name', value: 'Green Leaf Boutique', confidence: 0.95, evidence: [{ source: 'JSON-LD', selector: 'name', raw: '{"@type":"Store","name":"Green Leaf Boutique"}' }] },
          { id: 'id-2', lineId: 'identity', label: 'Business Type', value: 'Retail Store', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: '@type', raw: 'Store' }] },
          { id: 'id-3', lineId: 'identity', label: 'Description', value: 'Curated sustainable fashion, home goods, and artisan products', confidence: 0.9, evidence: [{ source: 'Meta', selector: 'og:description', raw: 'Curated sustainable fashion, home goods, and artisan products' }] },
          { id: 'id-4', lineId: 'identity', label: 'Location', value: 'Portland, OR', confidence: 0.85, evidence: [{ source: 'JSON-LD', selector: 'address', raw: '{"addressLocality":"Portland","addressRegion":"OR"}' }] },
        ],
      },
      {
        id: 'contacts',
        name: 'Contacts',
        colorDark: '#4ECDC4',
        colorLight: '#2980B9',
        visible: true,
        focused: false,
        stations: [
          { id: 'ct-1', lineId: 'contacts', label: 'Phone', value: '(503) 555-0178', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'a[href^="tel:"]', raw: '<a href="tel:+15035550178">' }] },
          { id: 'ct-2', lineId: 'contacts', label: 'Email', value: 'hello@greenleafboutique.com', confidence: 0.9, evidence: [{ source: 'HTML', selector: 'a[href^="mailto:"]', raw: '<a href="mailto:hello@greenleafboutique.com">' }] },
          { id: 'ct-3', lineId: 'contacts', label: 'Address', value: '1234 Hawthorne Blvd, Portland, OR 97214', confidence: 0.85, evidence: [{ source: 'JSON-LD', selector: 'address', raw: '{"streetAddress":"1234 Hawthorne Blvd"}' }] },
          { id: 'ct-4', lineId: 'contacts', label: 'Hours', value: 'Tue-Sat: 10am-6pm; Sun: 11am-5pm; Mon: Closed', confidence: 0.85, evidence: [{ source: 'JSON-LD', selector: 'openingHoursSpecification', raw: '[{"dayOfWeek":"Tuesday","opens":"10:00"}]' }] },
        ],
      },
      {
        id: 'services',
        name: 'Services',
        colorDark: '#45B7D1',
        colorLight: '#27AE60',
        visible: true,
        focused: false,
        stations: [
          { id: 'sv-1', lineId: 'services', label: 'Service', value: 'Personal Styling', confidence: 0.85, evidence: [{ source: 'HTML', selector: 'H3 > list > li', raw: 'Personal Styling' }] },
          { id: 'sv-2', lineId: 'services', label: 'Service', value: 'Gift Wrapping', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'H3 > list > li', raw: 'Complimentary Gift Wrapping' }] },
          { id: 'sv-3', lineId: 'services', label: 'Service', value: 'Online Shopping', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'H3 > list > li', raw: 'Online Shopping & Shipping' }] },
          { id: 'sv-4', lineId: 'services', label: 'Keyword', value: 'Sustainable, Eco-friendly, Artisan', confidence: 0.7, evidence: [{ source: 'Meta', selector: 'keywords', raw: 'Sustainable, Eco-friendly, Artisan, Fashion, Home' }] },
        ],
      },
      {
        id: 'pages',
        name: 'Pages',
        colorDark: '#F7DC6F',
        colorLight: '#F39C12',
        visible: true,
        focused: false,
        stations: [
          { id: 'pg-1', lineId: 'pages', label: 'Products', value: 'Shop All', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/shop"]', raw: '/shop' }] },
          { id: 'pg-2', lineId: 'pages', label: 'Products', value: 'New Arrivals', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/new"]', raw: '/new-arrivals' }] },
          { id: 'pg-3', lineId: 'pages', label: 'About', value: 'Our Mission', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/about"]', raw: '/about' }] },
          { id: 'pg-4', lineId: 'pages', label: 'Blog', value: 'Sustainability Journal', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/journal"]', raw: '/journal' }] },
          { id: 'pg-5', lineId: 'pages', label: 'Contact', value: 'Visit Us', confidence: 0.8, evidence: [{ source: 'HTML', selector: 'a[href="/visit"]', raw: '/visit' }] },
        ],
      },
      {
        id: 'entities',
        name: 'Entities',
        colorDark: '#BB8FCE',
        colorLight: '#8E44AD',
        visible: true,
        focused: false,
        stations: [
          { id: 'en-1', lineId: 'entities', label: 'Person', value: 'Emma Greenfield, Founder', confidence: 0.9, evidence: [{ source: 'JSON-LD', selector: 'founder.name', raw: 'Emma Greenfield' }] },
          { id: 'en-2', lineId: 'entities', label: 'Brand', value: 'Patagonia', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="Patagonia"]', raw: 'Patagonia' }] },
          { id: 'en-3', lineId: 'entities', label: 'Brand', value: 'Everlane', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="Everlane"]', raw: 'Everlane' }] },
          { id: 'en-4', lineId: 'entities', label: 'Brand', value: 'Coyuchi', confidence: 0.75, evidence: [{ source: 'HTML', selector: 'img[alt="Coyuchi"]', raw: 'Coyuchi' }] },
          { id: 'en-5', lineId: 'entities', label: 'Product', value: 'Organic Cotton Tote', confidence: 0.7, evidence: [{ source: 'JSON-LD', selector: 'Product.name', raw: 'Organic Cotton Tote' }] },
          { id: 'en-6', lineId: 'entities', label: 'Product', value: 'Beeswax Candle Set', confidence: 0.7, evidence: [{ source: 'JSON-LD', selector: 'Product.name', raw: 'Beeswax Candle Set' }] },
        ],
      },
      {
        id: 'tech',
        name: 'Tech',
        colorDark: '#82E0AA',
        colorLight: '#16A085',
        visible: true,
        focused: false,
        stations: [
          { id: 'tc-1', lineId: 'tech', label: 'CMS', value: 'Shopify', confidence: 0.95, evidence: [{ source: 'Script analysis', selector: 'signature: cdn.shopify.com', raw: 'cdn.shopify.com' }] },
          { id: 'tc-2', lineId: 'tech', label: 'Analytics', value: 'Google Analytics', confidence: 0.9, evidence: [{ source: 'Script analysis', selector: 'signature: google-analytics.com', raw: 'google-analytics.com' }] },
          { id: 'tc-3', lineId: 'tech', label: 'Marketing', value: 'Mailchimp', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: mailchimp', raw: 'mailchimp' }] },
          { id: 'tc-4', lineId: 'tech', label: 'Analytics', value: 'Facebook Pixel', confidence: 0.85, evidence: [{ source: 'Script analysis', selector: 'signature: connect.facebook.net', raw: 'connect.facebook.net' }] },
          { id: 'tc-5', lineId: 'tech', label: 'Design', value: 'Responsive Design', confidence: 0.8, evidence: [{ source: 'Meta', selector: 'meta[name="viewport"]', raw: 'width=device-width, initial-scale=1' }] },
        ],
      },
    ],
    transfers: [
      { id: 'tr-1', stationIds: ['id-4', 'ct-3'], lineIds: ['identity', 'contacts'], reason: '"Portland, OR" found in address' },
      { id: 'tr-2', stationIds: ['id-3', 'sv-4'], lineIds: ['identity', 'services'], reason: 'Similar values: Sustainable' },
      { id: 'tr-3', stationIds: ['sv-3', 'pg-1'], lineIds: ['services', 'pages'], reason: 'Similar values: Shopping' },
      { id: 'tr-4', stationIds: ['en-5', 'pg-2'], lineIds: ['entities', 'pages'], reason: 'Similar values: New products' },
    ],
  },
};
